from Queue1Clases import *
cola = Queue()
cola.push(1)
print("El primero es",cola.getFirstValue(),"El último es",cola.getLastValue())
cola.push(2)
print("El primero es",cola.getFirstValue(),"El último es",cola.getLastValue())
cola.push(3)
print("El primero es",cola.getFirstValue(),"El último es",cola.getLastValue())
cola.push(4)
print("El primero es",cola.getFirstValue(),"El último es",cola.getLastValue())
cola.push(5)
print("El primero es",cola.getFirstValue(),"El último es",cola.getLastValue())
cola.push(6)
print("El primero es",cola.getFirstValue(),"El último es",cola.getLastValue())
cola.showAllValues()

print("Al hacer pop", cola.pop().value)
print("El primero es",cola.getFirstValue())
cola.showAllValues()