from ListaDoblementeEnlazadaClases import *
lista = DoubleLinkedList()
lista.add(1)
lista.add(2)
lista.add(3)
lista.add(4)
lista.add(5)
lista.add(6)
lista.add(7)
lista.add(8)
lista.add(9)
print("Esta es la lista mostrada normalmente")
lista.show()

print("\n\n\n\n\n")
print("Esta en la lista mostrada en reversa")
lista.showReverse()